_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
  resource: "@AppBundle/Resources/config/admin.yml"
  prefix: /admin

front:
  resource: "@AppBundle/Resources/config/routing.yml"
  prefix: /

oneup_uploader:
    resource: .
    type: uploader