app:
    resource: "@AppBundle/Controller/"
    type:     annotation
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
_index:
    path: /
    defaults: {_controller: AppBundle:Default:index}
_testimonial:
    path:      /testimonial
    defaults:  { _controller: AppBundle:Testimonial:index }
_table_data:
    path: /list
    defaults: { _controller: AppBundle:TableData:index}
