app:
    resource: "@AppBundle/Controller/"
    type:     annotation
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
_index:
    path: /
    defaults: {_controller: AppBundle:Default:index}
_testimonial:
    path:      /testimonial
    defaults:  { _controller: AppBundle:Testimonial:index }
_table_data:
    path: /list
    defaults: { _controller: AppBundle:TableData:index}
