fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
  resource: "@AppBundle/Resources/config/admin.yml"
  prefix: /admin

front:
  resource: "@AppBundle/Resources/config/routing.yml"
  prefix: /


nmpolo_rest:
    resource: "@AppBundle/Controller/TestimonialRestController.php"
    type:     annotation
    prefix:   /rest

