services:
    sonata.admin.post:
        class: AppBundle\Admin\WomanAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - AppBundle\Entity\Woman
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]