app_woman:
    resource: "@AppBundle/Resources/config/routing/woman.xml"
    prefix:   /woman

app_galery:
    resource: "@AppBundle/Resources/config/routing/gallery.xml"
    prefix:   /gallery

app_image:
    resource: "@AppBundle/Resources/config/routing/image.xml"
    prefix:   /image

