services:
    liip_hello.world.controller:
        class: Liip\HelloBundle\Controller\HelloController
        arguments:
            view: @fos_rest.view_handler
            validator: @validator

    liip_hello.extra.controller:
        class: Liip\HelloBundle\Controller\ExtraController

    liip_hello.rest.controller:
        class: Liip\HelloBundle\Controller\RestController
        calls:
            - ['setContainer', [ @service_container ] ]

    liip_hello.phpcr.controller:
        class: Liip\HelloBundle\Controller\PHPCRController
        calls:
            - ['setContainer', [ @liip_hello.container ] ]

    liip_hello.container:
        parent: liip_container_wrapper.service
        arguments:
            index_0:
                doctrine_phpcr: true
                my_view: fos_rest.view_handler

    liip_hello.article.repository:
        class: Doctrine\ODM\PHPCR\DocumentRepository
        factory: [@doctrine_phpcr.odm.document_manager, "getRepository"]
        arguments:
            document_class_name: Liip\HelloBundle\Document\Article

    liip_hello.rss_handler:
        class: Liip\HelloBundle\View\RSSViewHandler

    liip_hello.view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', [ 'rss', [@liip_hello.rss_handler, 'createResponse'] ] ]

    # remove when https://github.com/sensio/SensioFrameworkExtraBundle/pull/115 is merged
    liip_hello.converter.doctrine.phpcr:
        class: %sensio_framework_extra.converter.doctrine.class%
        tags:
            - { name: request.param_converter}
        arguments:
            phpcr: @?doctrine_phpcr

    liip_hello.json_ld_serialization_handler:
        class: Liip\HelloBundle\Serializer\JsonLdSerializationHandler
        tags:
            - { name: jms_serializer.subscribing_handler}