<?php

namespace AppBundle\Entity;

/**
 * TestimonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonyRepository extends \Doctrine\ORM\EntityRepository
{
}
