<?php

namespace AppBundle\Entity;

/**
 * WomanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WomanRepository extends \Doctrine\ORM\EntityRepository
{
}
